version: '3'
services:
  hybrid-agi-chat:
    image: hybrid-agi-chat
    working_dir: /HybridAGI-chat
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi-chat
    env_file:
      - .env
    depends_on:
      - hybrid-agi-db
      - hybrid-agi-db-browser
    ports:
      - 8000:8000
    volumes:
      - ./archives:/HybridAGI/archives
      - ./documentation:/HybridAGI/documentation
      - ./programs:/HybridAGI/programs
  hybrid-agi-db:
    image: falkordb/falkordb:edge
    container_name: hybrid-agi-db
    ports:
      - 6379:6379
  hybrid-agi-db-browser:
    image: redislabs/redisinsight:latest
    container_name: hybrid-agi-db-browser
    depends_on:
      - hybrid-agi-db
    ports:
      - 8001:8001