version: '3'
services:
  hybrid-agi-chat:
    image: hybrid-agi-chat:0.0.0
    working_dir: /HybridAGI-chat
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-agi-chat
    depends_on:
      - falkordb
      - redis-insight
    ports:
      - 8501:8501
    volumes:
      - ./archives:/archives
      - ./documentation:/documentation
      - ./programs:/programs
  falkordb:
    image: falkordb/falkordb:latest
    container_name: falkordb
    ports:
      - 6379:6379
      - 7687:7687
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - falkordb
    ports:
      - 8001:8001

volumes:
  archives:
  documentation:
  programs: